#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define EECONFIG_USER_DATA_SIZE 4
#define TAPPING_TERM 100

#define RGBLIGHT_EFFECT_TWINKLE
#define RGBLIGHT_EFFECT_STATIC

#define DEBOUNCE 5
#define DEBOUNCE_DUAL_TIMER 50